services:
  mysql:
    image: mysql:8.0
    container_name: e-repository-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db2
      MYSQL_USER: e_repositori
      MYSQL_PASSWORD: secure_password_here
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - e-repository-network
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: e-repository-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=test_db2
      - DB_USER=e_repositori
      - DB_PASSWORD=secure_password_here
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=8080
    depends_on:
      - mysql
    networks:
      - e-repository-network
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: e-repository-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - api
    networks:
      - e-repository-network

volumes:
  mysql_data:

networks:
  e-repository-network:
    driver: bridge 